// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YUOPKM2EPtO2krCF50POL2Y9WnV96Hc',
    appId: '1:874966536972:web:facec23e23eb151c816f29',
    messagingSenderId: '874966536972',
    projectId: 'er-chandan-gupta',
    authDomain: 'er-chandan-gupta.firebaseapp.com',
    storageBucket: 'er-chandan-gupta.appspot.com',
    measurementId: 'G-CW8RJ0JPK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlto1r-1TrJ73y6e-abt7xtf1RXYes6JM',
    appId: '1:874966536972:android:000522f2f1b7a549816f29',
    messagingSenderId: '874966536972',
    projectId: 'er-chandan-gupta',
    storageBucket: 'er-chandan-gupta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFhfTftEcy-rQ0MEBWKAn7TxN9a9CDsdM',
    appId: '1:874966536972:ios:c391d2bbc6fa90f5816f29',
    messagingSenderId: '874966536972',
    projectId: 'er-chandan-gupta',
    storageBucket: 'er-chandan-gupta.appspot.com',
    iosClientId: '874966536972-nlgaltv1ecnkgmjdpq1t5u7hqtdliquf.apps.googleusercontent.com',
    iosBundleId: 'com.king.chandanGupta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFhfTftEcy-rQ0MEBWKAn7TxN9a9CDsdM',
    appId: '1:874966536972:ios:99e70c0acd74818a816f29',
    messagingSenderId: '874966536972',
    projectId: 'er-chandan-gupta',
    storageBucket: 'er-chandan-gupta.appspot.com',
    iosClientId: '874966536972-7h82dkd6d1kl6shvu1vn2rq5ojjs2s9c.apps.googleusercontent.com',
    iosBundleId: 'com.king.chandanGupta.RunnerTests',
  );
}
